### ISSUE TITLE
UI design with theming-in mind.

### ISSUE THREAD

**Issue by fortressia** [EchidnaHQ/Echidna#3]
As the plan is to make a drop-in replacement for VSCode that feels very familiar towards people already used with VSCode, we need to hack a lot of Qt's default UI, as VSCode does a lot of UI hacks too. ~~Qt has the QWidget:::setGraphicsEffect() method to add additional effect to the widget that isn't available in QSS. Including things like shadows, which is used a lot by VSCode for their panels.~~

- [x] ~~Implement barebones UI. ( See: #1. Miss a lot of stuff and still uses inline QSS, which is very taboo for me a web dev).~~
- [ ] ~~Add touchup effects and additional C++ styles to the UI to make it more simplistic with the UI hacks I said earlier.~~ Add tweaks to the UI to replicate the UX of VSCode.
    - [ ] Side Tab closes when you re-click the tab you already open.
    - [ ] ~~Change the look and feel to be like Visual Studio Code. (Custom widgets with some manual paintings).~~
- [ ] Connect this with the backend.~~

**Comment by Nefomemes** [comment]
Found this:

https://doc.qt.io/qt-5/qicon.html#Mode-enum

**Comment by Nefomemes** [comment]
It seems that we need to do some manual paintings by ourself, which honestly I'm not pro at currently, but after familiarizing with how to do manual painting in Qt, it might get easier in making these. Perhaps make it in a different repo.

Not sure whether we should put this in our MVP, but Echidna will eventually escalates to a whole new component library lol.
