### ISSUE TITLE
Decide on the direction of this project

### ISSUE THREAD

**Issue by FortressValkyrie** [EchidnaHQ/Echidna#6]
So, @vierofernando has yet to start developing on this project, while I'm still coding some logic of the program but hasn't been able to do much as I'm still learning Qt. On the other hand, I'm not confortable with its build system and package managers, and documentation. Conan's documentation sucks and while VCPKG's is better, it's still not the best.

So, as we haven't go much into the app's development, the direction of this project is still very very elastic. So,  here are our options:

- ## Rewrite in Rust and abandon C++.

@vierofernando is against this, and probably it's because he is a fan of C/C++. I initially followed him, but yeah, I'm thinking to change lang now and ignore opinions that I consider to be biased.

On the other hand, Rust is memory-safe, and it has built-in workflow features built by the Rust project itself, and their documentation is pretty neat. Ritual got the Rust Qt binding, and it's the latest LTS, just what we need.

- ## Stay in C++ and use VCPKG instead

- ## Whatever

**Comment by Nefomemes** [comment]
I have settled. We will move to Rust and GTK.

So this will obviously need to revert #1 and close #4.
